# Generated by Django 5.2.7 on 2025-11-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=23)),
                ('movie', models.CharField(max_length=23)),
                ('theatre', models.CharField(max_length=34)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
