# Generated by Django 5.2.7 on 2025-11-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=78)),
                ('email', models.EmailField(max_length=40)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
