# Generated by Django 5.2.7 on 2025-11-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
    ]
