# Generated by Django 5.2.7 on 2025-11-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='contact',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
