# Generated by Django 5.2.7 on 2025-11-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user1_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=40)),
                ('user_name', models.CharField(max_length=70)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
