# Generated by Django 5.2.7 on 2025-11-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_loginfrom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginFrom',
            new_name='User3',
        ),
    ]
