# Generated by Django 5.2.7 on 2025-11-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_loginfrom_user3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User3',
        ),
    ]
