# Generated by Django 5.2.7 on 2025-11-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_user3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bokking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=70)),
                ('theatre_name', models.CharField(max_length=30)),
                ('date', models.IntegerField()),
                ('time', models.TimeField()),
                ('movie_name', models.CharField(max_length=40)),
                ('type_of_seat', models.CharField(max_length=30)),
            ],
        ),
    ]
