# Generated by Django 5.2.7 on 2025-11-21 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_bokking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bokking',
        ),
    ]
