# Generated by Django 5.2.7 on 2025-12-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_delete_bokking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='password',
            field=models.CharField(verbose_name=90),
        ),
    ]
