# Generated by Django 5.2.7 on 2025-12-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user2_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='password',
            field=models.CharField(max_length=90),
        ),
    ]
