# Generated by Django 5.2.7 on 2025-11-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=70)),
                ('movie_name', models.CharField(max_length=50)),
                ('theater', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
